# https://launchpad.net/rustc
# https://packages.debian.org/stable/rustc
# https://software.opensuse.org/package/rust
image: rust:1.48.0-buster

rustfmt:
  script:
    - rustup component add rustfmt
    - cargo fmt -- --version
    - cargo fmt -- --check

test:
  script:
    - rustc --version && cargo --version
    - cargo build --verbose
    - cargo test
