# https://hub.docker.com/_/rust
# https://launchpad.net/rustc/+packages
# https://packages.debian.org/stable/rustc
# https://software.opensuse.org/package/rust
image: rust:1.75.0-slim-buster # should actually be trixie

rustfmt:
  script:
    - rustup component add rustfmt
    - cargo fmt -- --version
    - cargo fmt -- --check

test:
  script:
    - rustc --version && cargo --version
    - cargo build --verbose
    - cargo test
