#!/bin/bash

set -o errexit
set -o nounset

bump()
{
    local v="$1"

    sed -i '/^version /c version = "'"$v"'"' Cargo.toml
    sed -i "/^:version: /c :version: $v" doc/*.adoc
    cargo build
}

main()
{
    local v="${1:?specify version}"

    sed -i 's/Unreleased/'"$v - $(date --iso-8601=date)"'/' CHANGELOG.md
    bump "$v"
    git add --patch
    git commit --message "commitmsgfmt $v"
    git tag --annotate "v$v" --message "commitmsgfmt $v"

    bump "$v-GIT"
    local f=$(mktemp)
    awk '/^## / && !done { print "## Unreleased\n" ; done=1 } 1' CHANGELOG.md > $f
    mv $f CHANGELOG.md
    git add --patch
    git commit --message "Start next cycle"
}

main "$@"
