name: ci

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          - msrv
          - stable
          - nightly
          # Use nightly for these because that's what release does.
          - win-msvc
          - macos
        include:
          - build: msrv
            os: ubuntu-22.04
            rust: 1.63.0

          - build: stable
            os: ubuntu-22.04
            rust: stable

          - build: nightly
            os: ubuntu-22.04
            rust: nightly

          - build: win-msvc
            os: windows-2022
            rust: nightly

          - build: macos
            os: macos-12
            rust: nightly
    env:
      # Backtraces for panics.
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
